language: emacs-lisp
before_install:
  - curl -fsSkL https://gist.githubusercontent.com/rejeep/7736123/raw | sh
  - export PATH="/home/travis/.cask/bin:$PATH"
  - export PATH="/home/travis/.evm/bin:$PATH"
  - evm install $EVM_EMACS --use
  - cask
env:
  - EVM_EMACS=emacs-24.1-bin
  - EVM_EMACS=emacs-24.2-bin
  - EVM_EMACS=emacs-24.4-bin
  - EVM_EMACS=emacs-24.5-bin
script:
  - emacs --version
  - make test
notifications:
  webhooks: https://webhooks.gitter.im/e/fa0500ce49cab8dc8144
  on_success: change
  on_failure: always
  on_start: never
